// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.mjs";
import * as $_app from "./routes/_app.tsx";
import * as $api_login from "./routes/api/login.mjs";
import * as $api_name from "./routes/api/name.mjs";
import * as $api_thumb_title_ from "./routes/api/thumb/[title].mjs";
import * as $decade_year_ from "./routes/decade/[year].mjs";
import * as $index from "./routes/index.mjs";
import * as $movie_ratingKey_ from "./routes/movie/[ratingKey].mjs";
import * as $search from "./routes/search.mjs";
import * as $setname from "./routes/setname.mjs";
import * as $signin from "./routes/signin.mjs";
import * as $watch from "./routes/watch.mjs";
import * as $Scroll from "./islands/Scroll.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.mjs": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/login.mjs": $api_login,
    "./routes/api/name.mjs": $api_name,
    "./routes/api/thumb/[title].mjs": $api_thumb_title_,
    "./routes/decade/[year].mjs": $decade_year_,
    "./routes/index.mjs": $index,
    "./routes/movie/[ratingKey].mjs": $movie_ratingKey_,
    "./routes/search.mjs": $search,
    "./routes/setname.mjs": $setname,
    "./routes/signin.mjs": $signin,
    "./routes/watch.mjs": $watch,
  },
  islands: {
    "./islands/Scroll.tsx": $Scroll,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
