// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.js";
import * as $_app from "./routes/_app.js";
import * as $api_login from "./routes/api/login.js";
import * as $greet_name_ from "./routes/greet/[name].js";
import * as $index from "./routes/index.js";
import * as $signin from "./routes/signin.js";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.js": $_404,
    "./routes/_app.js": $_app,
    "./routes/api/login.js": $api_login,
    "./routes/greet/[name].js": $greet_name_,
    "./routes/index.js": $index,
    "./routes/signin.js": $signin,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
