name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

env:
  EDGEDB_INSTANCE: ${{ secrets.EDGEDB_INSTANCE }}
  EDGEDB_SECRET_KEY: ${{ secrets.EDGEDB_SECRET_KEY }}
  NAMES: ${{ secrets.NAMES }}
  PLEX_SERVER: ${{ secrets.PLEX_SERVER }}
  PLEX_TOKEN: ${{ secrets.PLEX_TOKEN }}
  PASSWORD: ${{ secrets.PASSWORD }}
  TOKEN: ${{ secrets.TOKEN }}




jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Cache
        uses: actions/cache@v4.2.0
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
          path: |
            node_modules
            lib

      - name: Pre-build step
        run: deno install --allow-scripts=npm:rescript-embed-lang@0.5.5,npm:rescript@12.0.0-alpha.7,npm:rescript@11.1.4

      - name: Build step
        run: "deno task build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "vlk-movie-night"
          entrypoint: "main.ts"
          root: "."
          
          
